# Generated by Django 5.1.4 on 2024-12-16 04:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='theatre',
        ),
        migrations.RemoveField(
            model_name='weeklyunavailability',
            name='theatre',
        ),
        migrations.AddField(
            model_name='customunavailability',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='day',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slot',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='movie_booking.screen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyunavailability',
            name='screen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_unavailabilities', to='movie_booking.screen'),
            preserve_default=False,
        ),
    ]
